### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by ddnexus** [freeroot/no-dark-overview#1]
Elegantly done!
Not that I am totally against the darkening, but that oval gradient not even smooth is totally awful! So thank you for saving my eyes!

What if I would like just to add a uniform darkening in the function that you left empty? Where could I find some documentation about how to do it?
Thanks!

**Comment by freeroot** [comment]
Hello,
I don't know but you can go to another extension page, https://github.com/freeroot/gnome-shell-darker-overview which is an extension about the same functionality but with more details.
Moreover, I propose a PR to it in order to merge our two extensions.
